[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "danbr25"
version = "1.0.0"
dependencies = [
    "matplotlib",
    "pandas",
    "scikit-learn",
    "urllib3"
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

